### ISSUE TITLE
Generating undefined host names for pixel ping urls

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud-pages#34]
Reading from all of the analytics we have recorded thus far, we appear to be recording hosts such as `http://pages.dcloud.org/examples` as `undefined/examples` in some instances.

**Comment by reefdog** [comment]
Pretty sure the culprit is `window.location.origin`. Need to replace with the proper combination of IE-safe `window.location` properties.

**Comment by reefdog** [comment]
Forgot to tag this issue in 2bece30cff88ac89628d5c4ca0dfbf4d45b2fe87.
