### ISSUE TITLE
Responsive behavior of page embed

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud-pages#4]
Page embeds currently scale up and down appropriate to their container, however as with many scalable objects, the utility of the experience changes depending on the viewable size.

Is there a better experience at low resolutions rather than just a mini version of the larger experience?

**Comment by reefdog** [comment]
> Is there a better experience at low resolutions rather than just a mini version of the larger experience?

Yes. :) We can set size classes now. Currently have three:
- Under 200px, just show the title, image thumbnail, and link icon. Link everything back to DC.
- From 200-299px, show the full embed experience but with interface stripped down (no icons only on action buttons, etc.)
- At 300px+, get the full experience.

We can expand upon that as necessary.
